Zip code
Marwan01/covid-helpline pull request #27
Opened 2020-03-20 18:53 UTC by glennparham

I am integrating [this feature](https://www.notion.so/New-Current-Case-Notification-76018a8f2ef74ed8b3bf958c76271008).

I have added zip_code.py.  Trigger the **get_state_stats(zip_code)** function and it will automatically return the properly formatted response as a string.

EXAMPLE RESPONSE: 
<img width="667" alt="Screen Shot 2020-03-20 at 6 31 39 AM" src="https://user-images.githubusercontent.com/19394146/77196861-8a00f000-6aba-11ea-8eb4-316955b5fff6.png">

2020-03-20 21:21 UTC, Marwan01 reviewed
Return only state info (comment out county part for now, but leave in code as it might come useful later)

Add number of recovered, and deaths.
Add the yesterday part, and growth rate to the state/country regular search message so it’s conform
I like your formatting where you have the state returned in caps in it’s own line. Do you mind changing the state/country  message to match that too?
So in a nutshell, make the country/state message and the zip message the same.
In the welcome message, add “zip” as follows: [ - Text country/state/“zip” to get the most up to date report.. ]

I LOVE the latest updates from governor. I do find twitter inaccurate tho. I would say since we want to have one small and clean message for the count report, to remove it from that response. However, we have a “news” route, and we could have a different response that will get your governor’s updates, potentially from newsapi or twitter. We could send something like “news” Missouri and you can start getting your governor’s news that way.

2020-03-20 21:29 UTC, Marwan01 commented
Forget about: Return only state info (comment out county part for now, but leave in code as it might come useful later)

County info is actually awesome when available, and is implemented nicely.

2020-03-21 18:41 UTC, AlexAndrei98 commented
Glenn, Looks great! I added just a little comment!
Do you think that it would be possible to integrate the growth info and the daily information in the general response message as well? Do you think that would be pretty straight froward to implement?

2020-03-21 18:42 UTC, AlexAndrei98 requested changes

2020-03-21 18:42 UTC, AlexAndrei98 commented on src/twillio_utils.py
> +from .zip_code import get_zip_code_stats
I would remove the `.` from here since it was giving some errors with the deploymebnt

2020-03-23 00:28 UTC, AlexAndrei98 approved these changes
LGTM let’s add a ticket to add some tests for these cases as well

2020-03-23 02:26 UTC, merged

2020-03-23 02:27 UTC, Marwan01 commented
Thank you for your contribution!